/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.5/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application
    `maven-publish`
    id("com.jfrog.bintray") version "1.8.5"
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}
val main: String = "org.openjdk.asmtools.Main"
application {
    // Define the main class for the application.
    mainClassName = main
}
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withJavadocJar()
    withSourcesJar()
}
tasks {
    jar {
        manifest {
            attributes(mapOf("Main-Class" to main))
        }
    }
}
publishing {

    publications {
        register<MavenPublication>("bintray") {
            from(components["java"])
            groupId = "me.enterman"
            artifactId = "asmtools"
            version = "1.0.1"
        }
    }
}
fun findProperty(s: String) = project.findProperty(s) as String?

bintray {
    user = System.getenv("bintrayUser")
    key = System.getenv("bintrayApiKey")
    // publish = true
    setPublications("bintray")
    pkg(delegateClosureOf<com.jfrog.bintray.gradle.BintrayExtension.PackageConfig> {
        repo = "asmtools"
        name = "asmtools"
        userOrg = user
        setLabels("asmtools")
        version(closureOf<com.jfrog.bintray.gradle.BintrayExtension.VersionConfig> {
            name = "1.0.0"
        })
    })
}
